.TH xp "1" "June 17 2013" "Julian K. Arni"  "The xp Manual"

.SH NAME

xp - The pipe wildcard.

.SH SYNOPSIS

\fBxp\fR [\fB-p \fR| \fB--pager\fR] [\fB-m \fR| \fB--menu\fR]

.RS 3
[\fB-p\fR | \fB--pager\fR] [(\fB--m=\fR | \fB--menu=\fR) <regexgroup>]
.RE

.SH DESCRIPTION

\fBxp\fR partially evaluates a sequence of piped commands, stopping at
its own invocation. It then allows any further commands specified at its
prompt to be added to the pipe in its stead. It can be seen as a "pipe
wildcard," and is useful in seeing a partial evaluation (or perhaps more
accurately, decomposition) of a pipeline, and modifying that pipeline
accordingly.

\fBxp\fR is meant to be used with pipes:

.RS 5
\fI progA | progB ... | \fB xp | \fI progX ...\fR
.RE

Without any flags, \fBxp\fR prints the output of of progA, progB ... to tty
(without passing it to progX ...), and waits for a user command[s]. This
command is executed and passed the output of the pipes up to \fBxp\fR as
\fIits\fR input. The output of that is then passed on to progX ... .

Thus, running:

.RS 5
\fI progA | progB ... | \fB xp \fI | progX ...\fR
.RE

and then typing \fI[cmd]\fR at the prompt is ultimately equivalent to 

.RS 5
\fI progA | progB ... | \fR [cmd] |\fI progX ...\fR
.RE

Except that the partial result is printed to the terminal. Similarly, hitting
\fBRETURN\fR (without any commands) at the prompt is equivalent to not using xp
in the first place (except, once again, for the partial result of the pipe
being printed to the console).

At \fBxp\fR's prompt too \fBxp\fR can be invoked. This can be useful for
progressively filtering some input (see the \fBEXAMPLES\fR section below).

.SH OPTIONS

\fB-m\fR
.RS 5 
Number the lines piped to \fBxp\fR and prompt the user to select one.
The line will be piped out by \fBxp\fR. (This is much like the shell "select".)
Multiple lines can be chosen, in which case the numbers must be separated by
commas.
.RE

\fB--m=\fR<regexgroup>
.RS 5 
\fBxp\fR will numerically label each match in the input string of  \fIthe first
group\fR in the regex listed under the group \fI<regexgroup>\fR in the
\fB~/.extendp.cfg\fR file. Choosing a number at the \fBxp\fR prompt produces
the corresponding match as \fBxp\fR's output. Multiple numbers, separated by
commas, can also be used.

\fBxp\fR uses the
Perl-compatible regular expression syntax provided by Glib.  
.RE

.SH EXAMPLES 

\fB cd `find . -name "myfile*" | xp | xargs dirname`\fR  
.RS 5 
Select one of the files found by \fBfind\fR to \fBcd\fR into its directory.
.RE

.SH SEE ALSO

.SH HISTORY
